### ISSUE TITLE
Progress Bar Button isn't disabled with ButtonOpts.disabled set to true, but only when running --prod.

### ISSUE THREAD

**Issue by alan-g-chen** [michaeldoye/mat-progress-buttons#10]
**Describe the bug**
I'm using progress-bar-button (which is awesome, by the way!) When setting the provided ButtonOpts `disabled` attribute to `true`, the button properly appears disabled when running locally. However, when running with --prod, the button is not disabled, though the attribute is properly set.

**To Reproduce**
1. Add a progress-bar-button.
2. Associate a ButtonOpts object.
3. Set ButtonOpts.disabled attribute to 'true'
4. Run `ng serve`
5. Button appears disabled.
6. Run `ng serve --prod`
7. Button does not appear disabled.

**Expected behavior**
Button should appear disabled with running with --prod.

**Screenshots**
Button appearance with --prod:
![image](https://user-images.githubusercontent.com/33558695/45664055-c1a26c80-babe-11e8-8980-fbf160b7656b.png)

ButtonOpts values:
![image](https://user-images.githubusercontent.com/33558695/45664045-b0596000-babe-11e8-9b88-7acc9268cf10.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version 69.0.3497.92 (Official Build) (64-bit)

**Comment by michaeldoye** [comment]
Thanks for the report, this will be fixed in the next release.

**Comment by michaeldoye** [comment]
fixed in [7.0.4](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.0.4)
