### ISSUE TITLE
Add mat-icon to the button

### ISSUE THREAD

**Issue by medbejimbj** [michaeldoye/mat-progress-buttons#13]
Hello,

I'd like to add mat-icon to the button while the button is not submitted.  is it possible ?
Thanks

**Comment by michaeldoye** [comment]
Update:  [7.1.2](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.1.2) includes icons for Fab buttons. Icons for normal buttons coming soon 👍

**Comment by frabanca** [comment]
Hi @michaeldoye , do you have an estimate delivery time for icons in normal buttons?

Maybe something like this:
```
const loadFromFileBtnOptions: MatProgressButtonOptions = {
    active: false,
    text: 'Load from File',
    spinnerSize: 19,
    raised: true,
    stroked: true,
    flat: false,
    fab: false,
    buttonColor: 'primary',
    spinnerColor: 'primary',
    fullWidth: false,
    disabled: false,
    mode: 'indeterminate',
    fontSet: 'fal', // For fontawesome "fas", "far", "fal", "fad" and "fab" while for standard angular icons "" (empty)
    icon: 'fa-user' // icon name
  };
```

An extra feature could be some extra options whitch will allow user to set a custom icon as a spinner. Font-Awesome has some nice ones.

Thanks and have a good day!

**Comment by michaeldoye** [comment]
@frabanca Full icon support for the normal buttons will be coming soon-ish. In the meantime, the `fab-button` now has full icon support (included in the next release)

**Comment by frabanca** [comment]
Yeah, I've used those icon type (they are awesome!) but I also need icons in normal buttons due to UI consistency. I will wait for the next release, maybe it will be before our project delivery :P :)
Thanks again and have a good day!

**Comment by michaeldoye** [comment]
This feature will be included in the next release 🥇
