### ISSUE TITLE
Handle fxFlex.lt-md="100%"

### ISSUE THREAD

**Issue by jegjessing** [michaeldoye/mat-progress-buttons#14]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [x] feature request
```

### OS and Version?
Linux

### Versions
Angular CLI: 6.2.4
Node: 8.12.0
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cdk                      6.4.7
@angular/cli                      6.2.4
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2

### Repro steps
Add fxFlex... to element
Resize browser to see if the flex work

### The log given by the failure
No reason since this does not crash or fail

### Desired functionality
Honor the flex settings given as arguments

**Comment by michaeldoye** [comment]
I can reproduce this, can you provide a demo? You can use [this stackblitz](https://stackblitz.com/edit/mat-progress-buttons-demo).

Thanks
