### ISSUE TITLE
mat-flat-button support?

### ISSUE THREAD

**Issue by rynop** [michaeldoye/mat-progress-buttons#16]
How do you render a `mat-flat-button`?  I don't see it in the source, so this is probably a feature request.

**Comment by michaeldoye** [comment]
ahh... they added a new button. Will update with the flat button and ping you when it's published. Thanks for reporting!

**Comment by rynop** [comment]
Thanks. I would have done a PR but it didn't look like it was easy as adding `[class.mat-flat-button]="options.flat"`

**Comment by michaeldoye** [comment]
Fixed in [v7.1.1](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.1.1)
