### ISSUE TITLE
Button type attribute

### ISSUE THREAD

**Issue by florentcm** [michaeldoye/mat-progress-buttons#18]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
I could not find a way to fill the **type attribute** of the generated button. 
Might be nice to add it to the options, accepting values _submit_, _reset_ or _button_.

**Comment by michaeldoye** [comment]
Agreed, this would be useful, thanks 👍

**Comment by michaeldoye** [comment]
added in [7.1.2](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.1.2)
