### ISSUE TITLE
Lazy Loading Issue.

### ISSUE THREAD

**Issue by EnhuiGuo** [michaeldoye/mat-progress-buttons#2]
i import the module on app.module and works fine. But i import to my lazy loaded module, i got the error "BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead."  
Here is my lazy loaded module: 

import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { HeroListComponent } from './hero-list.component';
import { HeroDetailComponent } from './hero-detail.component';

import { HeroService } from './hero.service';
import { RegisterService } from '../register.service';

import { HeroRoutingModule } from './heroes-routing.module';
import { MatProgressButtons } from 'mat-progress-buttons';

@NgModule({
    imports: [
        CommonModule,
        FormsModule,
        HeroRoutingModule,
        MatProgressButtons
    ],
    declarations: [
        HeroListComponent,
        HeroDetailComponent
    ],
    providers: [HeroService, RegisterService]
})
export class HeroesModule { }

Can some one help me?

**Comment by michaeldoye** [comment]
I will need to test this package with Lazy loaded modules and update accordingly. Thanks for reporting!

**Comment by michaeldoye** [comment]
Fixed in [v1.3.2](https://github.com/michaeldoye/mat-progress-buttons/releases)

You can find a working DEMO with lazy loading here - [StackBlitz](https://stackblitz.com/edit/angular-doxhpg)
