### ISSUE TITLE
Spinner Color

### ISSUE THREAD

**Issue by simeon4110** [michaeldoye/mat-progress-buttons#20]
This is a simple feature request.

How would I go about using a color other than 'accent' or 'primary' as the spinner color?

**Comment by michaeldoye** [comment]
You could either:
 
1. Set up a [custom theme as per Angular Material](https://material.angular.io/guide/theming)
2. Try setting up [custom styles for the Material components](https://material.angular.io/guide/customizing-component-styles)

In any case, the spinner color is not handled by the library, but rather by your apps configuration of the Angular Material theme. But I guess you could also just override the SVG styles with some CSS trickery.

**Comment by simeon4110** [comment]
Hey, thank you very much for the leads. I tried to override the default styling in the mat-theme, but I couldn't find the proper selector. I'll look into it further. This is a great package and really helps keep form code clean and straightforward.
