### ISSUE TITLE
disable button allows interaction with the button click event

### ISSUE THREAD

**Issue by jorgeluis1706** [michaeldoye/mat-progress-buttons#23]
Hi, i tried to prevent the event click trigger with disable:true but yet in this state allow the interaction with the mouse click event, please if you can help me i thank you.

**Comment by michaeldoye** [comment]
I'm not sure I understand. Do you want to disable the button AND have access to mouse event? or does the mouse event still fire when the button is disabled?

**Comment by jorgeluis1706** [comment]
no, what I wanted to say is that even if you put the button in disabled: true the button continues executing the click event.

you can try what I tell you here https://stackblitz.com/edit/mat-progress-buttons-demo-iulcmm.

**disabled is equal to true and still executes the click action**

**Comment by michaeldoye** [comment]
Ok, got it, thanks for reporting. Will be fixed in the next release.

**Comment by jorgeluis1706** [comment]
thanks so much! i really need it.

**Comment by michaeldoye** [comment]
FIxed in [8.1.0](https://github.com/michaeldoye/mat-progress-buttons/blob/v8.0.1/CHANGELOG.md)

run `npm install --save mat-progress-button` to update.

Please note the [BREAKING CHANGES](https://github.com/michaeldoye/mat-progress-buttons/blob/v8.0.1/CHANGELOG.md#breaking-changes)

**Comment by jorgeluis1706** [comment]
Thanks man, please, verify the comment that i have made in https://github.com/michaeldoye/mat-progress-buttons/commit/b8ec4b3#diff-c0c644839a778af4e11908b62efbd3fcR16.
