### ISSUE TITLE
fullWidth option is  not working

### ISSUE THREAD

**Issue by chukiatt** [michaeldoye/mat-progress-buttons#25]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

**Comment by chukiatt** [comment]
I like your button. It's very cool. but i have a little few about button width, i set fullwidth option to 'true' but it alway relate width to text width.

**Comment by michaeldoye** [comment]
Hi, thanks for the report, only the spinner button currently supports full width. Bar button full width support will be coming soon. I have created a ticket for this which you can track [here](https://github.com/michaeldoye/mat-progress-buttons/issues/27)
