### ISSUE TITLE
mat-bar-button does not work in --prod

### ISSUE THREAD

**Issue by jorgeluis1706** [michaeldoye/mat-progress-buttons#26]
hi, i am having a problem with the buttons in prod environment, these doesn't work, please help me with that.

I see that you had recieved the same issue previously but in other order. https://github.com/michaeldoye/mat-progress-buttons/issues/6

note: i assume that the problem is the bntClick because i use a mat-bar-button without btnclick in a form and work perfectly

**Comment by michaeldoye** [comment]
Thanks for the report. I can't seem to reproduce this, is there a specific error you are getting? I have tested a prod version of this, [here](https://stackblitz.com/edit/mat-progress-buttons-demo) and [here](https://mat-progress-buttons.firebaseapp.com/home)
