### ISSUE TITLE
npm WARN mat-progress-buttons@8.0.3 requires a peer of tsickle@^0.34.0 but none is installed. You must install peer dependencies yourself.

### ISSUE THREAD

**Issue by hisham** [michaeldoye/mat-progress-buttons#28]
- [X] bug report -> please search issues before submitting
- [ ] feature request

I get this warning when npm installing this package. Shouldn't tsickle be in your devDependencies? 

"tsickle": "^0.34.0"

**Comment by michaeldoye** [comment]
Thanks for reporting, will be fixed in the next release

**Comment by jpike88** [comment]
Waiting on this, it's adding bloat to my app payload

**Comment by michaeldoye** [comment]
fixed in [8.0.4](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v8.0.4)

**Comment by hisham** [comment]
It doesn't seem like this is fixed yet - tsickle was added to devDependencies but not removed from dependencies. 

Also is `@angular-devkit/schematics` really needed in dependencies? Seems like should be moved to devDependencies.
