### ISSUE TITLE
Feature request: global MatProgressButtonOptions

### ISSUE THREAD

**Issue by muliyul** [michaeldoye/mat-progress-buttons#30]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
Angular CLI: 7.1.3
Node: 10.15.3

### Desired functionality
Have `[options]` input be an optional [partial](https://www.typescriptlang.org/docs/handbook/advanced-types.html#mapped-types) of MatProgressButtonOptions and allow `forRoot` to accept an optional MatProgressButtonOptions which will be the default configuration for buttons (input overrides defaults set in `forRoot`.

**Comment by michaeldoye** [comment]
Indeed, I have had this idea in mind for sometime now, thanks for the feedback, I will include this in the next release.
