### ISSUE TITLE
Support for @angular/material 8.0.0

### ISSUE THREAD

**Issue by francovp** [michaeldoye/mat-progress-buttons#35]
Please, the `package.json` needs to be updated to support `@angular/material 8.0.0`

Thanks in advance

**Comment by Cacanny** [comment]
Does package break when trying to update?

**Comment by michaeldoye** [comment]
I will be updating to angular 8 in the coming days. Have been super busy lately. @Cacanny your application should not break because of this package when updating.

**Comment by francovp** [comment]
Hello, any update on this?

**Comment by francovp** [comment]
Just making sure this project is not abandoned

**Comment by michaeldoye** [comment]
Not abandoned :) just super busy right now with work. But feel free to make a PR if you have the time. Otherwise I have some free time coming up in the next month or so and intend on making a lot updates during that time. Apologies for the delay... Unfortunately, work pays, open source does not :(
