### ISSUE TITLE
mat-bar-button icon doesn't work

### ISSUE THREAD

**Issue by mrnewrochelle** [michaeldoye/mat-progress-buttons#40]
Hi.
 to the
 `<mat-bar-button 
  [options]="barButtonOptions" 
  (btnClick)="someFunc2()">
</mat-bar-button>`

I want to remove the text and just show an icon, something like this:
`barButtonOptions: MatProgressButtonOptions = {
    active: false,
    text: ' ',
    buttonColor: 'accent',
    barColor: 'primary',
    raised: true,
    stroked: false,
    mode: 'indeterminate',
    value: 0,
    disabled: false,
    fullWidth: false,
     icon: 'favorite'
  }`

But the button disappears , it just doesn't work.
Am I doing something wrong?

Thanks 
[Im Testing here ](https://stackblitz.com/edit/mat-progress-buttons-demo?file=app%2Fapp.component.ts)

**Comment by michaeldoye** [comment]
Dup of #13
