### ISSUE TITLE
is it work IE 11

### ISSUE THREAD

**Issue by mateBe95** [michaeldoye/mat-progress-buttons#43]
Is this library working on IE 11?

**Comment by michaeldoye** [comment]
As long as you have pollyfills enabled, it should work fine

**Comment by insomnia1337** [comment]
no there is the problem with styles on IE 11, the spinner is on the right. Try to open your demo version on ie 11, u will see

**Comment by michaeldoye** [comment]
I see, thanks :)

**Comment by AndreyBespamyatnov** [comment]
`On August 17, 2020, Microsoft published a timeline indicating that Microsoft Teams will stop supporting Internet Explorer 11 on November 30, 2020 whereas Microsoft 365 products will end Internet Explorer 11 support on August 17, 2021`
[Source](https://en.wikipedia.org/wiki/Internet_Explorer_11#:~:text=On%20August%2017%2C%202020%2C%20Microsoft,support%20on%20August%2017%2C%202021.)

So I think we should not spend any time on it.

**Comment by michaeldoye** [comment]
closing because IE will finally be retired next month
