### ISSUE TITLE
MatProgressButtons module is not present in build with --prod flag

### ISSUE THREAD

**Issue by jony543** [michaeldoye/mat-progress-buttons#6]
When I build my app in dev mode the buttons works perfectly, but when I used --prod flag the click events weren't executing and when I looked into it I found the entire module is not include in the final js build.

I have seen a similar issue but it is marked as fix. 

I am using version 6.0.1

Thanks.

**Comment by michaeldoye** [comment]
Thanks for the bug report.

It seems to be an issue when using `onClick` , you can use `click` instead which should work.

**Comment by michaeldoye** [comment]
fixed in [7.0.4](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.0.4)

**Comment by jony543** [comment]
Thanks!
