### ISSUE TITLE
Not compatible with Angular Material 9

### ISSUE THREAD

**Issue by ioannist** [michaeldoye/mat-progress-buttons#62]
Getting the error:
ERROR in Cannot resolve type entity ɵngcc4.MatButtonModule to symbol

when using Angular Material ^9.0.0-rc.4

It's an easy fix...
Components can no longer be imported through @angular/material.
Use the individual secondary entry-points, such as @angular/material/button.

**Comment by michaeldoye** [comment]
Thanks for reporting. Will fix it for the next release

**Comment by MRMokwa** [comment]
Could we have a @next version like angular have? Angular 9 is around the corner with RC9 and it would be nice habing it roling before that.

**Comment by zepekenio** [comment]
Hi, any news ?

**Comment by michaeldoye** [comment]
@zepekenio super busy at the moment, but should have some free time coming up to fix this.

**Comment by newmesiss** [comment]
from what I saw is just an import problem
now it must be imported for each component used separately

**Comment by gwenaellarmet** [comment]
Hello since Angular 9 is out, is there any news on this issue ?

**Comment by lucabrasi83** [comment]
Part of the fix I believe is to change the @angular/material imports and add a Type to ModuleWith Providers in module:

```typescript
import {MatButtonModule} from '@angular/material/button'
import { MatProgressBarModule } from '@angular/material/progress-bar'
import {MatRippleModule} from '@angular/material/core';
import { MatIconModule } from '@angular/material/icon';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';

export class MatProgressButtonsModule {
  static forRoot(): ModuleWithProviders<MatProgressButtonsModule> {
    return {
      ngModule: MatProgressButtonsModule
    };
  }
}
```

**Comment by jochenonline** [comment]
@lucabrasi83 Could you provide a PR to accelerate the process?

**Comment by NDBman** [comment]
> @lucabrasi83 Could you provide a PR to accelerate the process?

If I can get the right to push I'm more than glad to make a PR.

**Comment by lujakob** [comment]
@michaeldoye: I created a PR with the Angular 9 update. Would be happy if you could have a look as it's a blocker for several of my projects. Thanks :)

**Comment by michaeldoye** [comment]
Thank you to @lujakob! The new version is now available. Apologies for the delay, and thank you for the patience. <3
