### ISSUE TITLE
Support Angular10

### ISSUE THREAD

**Issue by spock123** [michaeldoye/mat-progress-buttons#69]
` Package "mat-progress-buttons" has an incompatible peer dependency to "@angular/cdk" (requires "^9.1.1", would install "10.0.0").`

Thank you

**Comment by michaeldoye** [comment]
Another version already, nice. thanks for reporting. Will add support for angular 10 soon

**Comment by Warwizza** [comment]
Is there any progress or timeline for this? Hopefully you will find time for this soon. 

Thanks

**Comment by jeremylcarter** [comment]
Did anyone force their ng update @angular/material , does this library work with Angular 10 if you ignore the compatibility warning?

**Comment by louis-lau** [comment]
Yes, it's working fine for me despite the compatibility warning. Could always try it yourself and `git reset` if it doesn't work out 😉.

**Comment by gwenaellarmet** [comment]
Hello, It's working also in angular 11; but it would be nice to update the dependencies so we don't have to force the update ;)
