### ISSUE TITLE
Using tooltip with mat progress buttons

### ISSUE THREAD

**Issue by jorgeluis1706** [michaeldoye/mat-progress-buttons#70]
Hi, **there is a way to use tooltip with the buttons, with mat-tooltip or other**?

**Comment by michaeldoye** [comment]
Indeed, `matTooltip` works:

```
<mat-bar-button 
  matTooltip="Info about the action"
  [options]="barButtonOptions" 
  (btnClick)="someFunc2()">
</mat-bar-button>
```

<img width="304" alt="Screenshot 2020-07-06 at 22 35 37" src="https://user-images.githubusercontent.com/4910775/86639523-4bdffb80-bfd9-11ea-9b49-c60403306ffb.png">

Here you can [see a demo](https://stackblitz.com/edit/mat-progress-buttons-demo-er5rli?file=app/app.component.html).
