### ISSUE TITLE
Moving to the Angular Lib project type

### ISSUE THREAD

**Issue by AndreyBespamyatnov** [michaeldoye/mat-progress-buttons#72]
May I move this project to the angular lib project type? I see a lot of benefits from that.

I think we will have better support within the angular ecosystem and it would be way easier to contribute. 
Like one of the issue is a bit hard to update the karma framework, etc.

So I just want to know would my work be accepted or not)

Thanks!

**Comment by michaeldoye** [comment]
Yes, please go ahead and do so if you have the time, it would be very much appreciated!
