### ISSUE TITLE
Add support for angular 12

### ISSUE THREAD

**Issue by Shavais-Siddiqui** [michaeldoye/mat-progress-buttons#78]
ound: @angular/cdk@12.0.2
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^12.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^11.0.3" from mat-progress-buttons@9.2.1
npm ERR! node_modules/mat-progress-buttons

**Comment by cristiansandru11** [comment]
+1
