### ISSUE TITLE
Please add support for button to not be disabled after click

### ISSUE THREAD

**Issue by fimius23** [michaeldoye/mat-progress-buttons#8]
**Is your feature request related to a problem? Please describe.**
I've been going through the Material Design documents and they have an [example](https://material.io/design/components/progress-indicators.html#circular-progress-indicators) where the button text is replaced with a spinner and the button does not become disabled (It's in the **Integrating with actions** section).

**Describe the solution you'd like**
I'd like a button option where I could set whether or not to disable the button when it's clicked. I'd also like it if the `spinner` class was not added if there is no text (since we don't need the margins). I do like the idea of the `cursor: not-allowed` on button click though.

**Comment by michaeldoye** [comment]
Great suggestion, thanks. There will be a new release in the next few days which implements your suggestion.

**Comment by michaeldoye** [comment]
Implemented in [7.0.4](https://github.com/michaeldoye/mat-progress-buttons/releases/tag/v7.0.4)
