### ISSUE TITLE
Update peer deps for Angular 12

### ISSUE THREAD

**Issue by midgleyc** [michaeldoye/mat-progress-buttons#85]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

In 9.3.1, both the root and the demo project have been updated to Angular 12, but the [main package.json](https://github.com/michaeldoye/mat-progress-buttons/blob/master/projects/mat-progress-buttons/package.json) is still showing Angular 11.

**Comment by michaeldoye** [comment]
Thanks, will update it
