### ISSUE TITLE
NullInjectorError after upgrade to version 9.3.1 with Angular 12

### ISSUE THREAD

**Issue by lujakob** [michaeldoye/mat-progress-buttons#86]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
```

### OS and Version?

Mac OS in Chrome

### Versions

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@angular/cdk                    12.1.0
@angular/flex-layout            9.0.0-beta.31
@angular/material               12.1.0
@schematics/angular             8.3.29
rxjs                            6.6.7
typescript                      4.3.4

### Repro steps

Install mat-progress-buttons 9.3.1 and load page that contains a spinner button

### Mention any other details that might be useful

<img width="443" alt="Bildschirmfoto 2021-07-30 um 14 23 38" src="https://user-images.githubusercontent.com/886152/127652869-dd0c01e9-25ac-45cc-b234-34e96f2f7fc9.png">

**Comment by bartez** [comment]
Did you use **MatProgressButtonsModule.forRoot()** function in your app.module.ts like that:
`import { MatProgressButtonsModule } from 'mat-progress-buttons';

@NgModule({
  declarations: [AppComponent, ...],
  imports: [MatProgressButtonsModule.forRoot(), ...],  
  bootstrap: [AppComponent]
})
export class AppModule {
}
`

**Comment by lujakob** [comment]
@bartez using ".forRoot()" in app.module.ts worked. Apparently up until version 9.2.1 it worked without it, that's why we did not have it applied.
